FROM maven:3-eclipse-temurin-11-alpine

ENV GEN_DIR=/opt/swagger-codegen
# Add Java memory settings
ENV JAVA_OPTS="-Xms512m -Xmx1024m -XX:MaxPermSize=256m"
ENV MAVEN_OPTS="-Xms512m -Xmx1024m -XX:MaxPermSize=256m"

RUN apk add --update nodejs git yarn

# Create directory for your files
RUN mkdir -p /data/input

# Copy files from host into container
# Note: Files should be in the build context directory
COPY ./files/ /data/input/

RUN git clone https://github.com/swagger-api/swagger-codegen

# Change directory to the swagger-codegen directory before running Maven
RUN cd swagger-codegen && MAVEN_OPTS="$MAVEN_OPTS" mvn -am -pl "modules/swagger-codegen-cli" package

WORKDIR /data

ENTRYPOINT ["/bin/sh"]
