FROM jimschubert/8-jdk-alpine-mvn:1.0

ENV GEN_DIR /opt/swagger-codegen

RUN apk add --update nodejs git

RUN git clone https://github.com/swagger-api/swagger-codegen &&\
    cd ./../swagger-codegen &&\ 
    mvn -am -pl "modules/swagger-codegen-cli" package

WORKDIR /data

ENTRYPOINT ["/bin/sh"]